[gcp_service_account]
type = "service_account"
project_id = "beercanraceapp"
private_key_id = "aacc89b07729a5d5610d6b1093ac2adcccf9226d"
private_key = """-----BEGIN PRIVATE KEY-----
MIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQDXJW7lfbmF/JEk
VXRDh8M69fGhsQQzkzAJM+h6ISfMnmTyRGM6il9TyQMMzmjN413PhBgkvUcf+1O8
...rest of your key...
Wu+4WMqr6FdxhUC9P1gywgs=
-----END PRIVATE KEY-----"""
client_email = "beercanraceapp@beercanraceapp.iam.gserviceaccount.com"
client_id = "112282543966946387098"
auth_uri = "https://accounts.google.com/o/oauth2/auth"
token_uri = "https://oauth2.googleapis.com/token"
auth_provider_x509_cert_url = "https://www.googleapis.com/oauth2/v1/certs"
client_x509_cert_url = "https://www.googleapis.com/robot/v1/metadata/x509/beercanraceapp@beercanraceapp.iam.gserviceaccount.com"
universe_domain = "googleapis.com"
